[SQL] Always generate code using handles for circuit inputs/outputs
feldera/feldera pull request #1213
Opened 2023-12-29 21:28 UTC by mihaibudiu

Is this a user-visible change (yes/no): no

Fixes #1207 
Fixes #1204 

Previously the Rust generated by the compiler had two different structures depending on whether we test or deploy as a pipeline. With this PR we bring the two structures much closer. There is still a difference: tests use a strongly-typed API for the stream handles that are the circuit I/Os, while the pipeline uses the Catalog API to obtain untyped stream handles.

Merging this properly would require a fix for #1208. In the meantime I have disabled the check that the panic message is adequate.

2023-12-29 21:30 UTC, mihaibudiu commented
@ryzhyk this has some Rust code, please review. Some of the changes may clash with the fixes planned for #1208.

2023-12-29 21:32 UTC, mihaibudiu commented
@lalithsuresh I will spare you a review request for this one, the changed code isn't really readable since it essentially generates Rust strings. The fact that the tests pass is a good reassurance that it does the right thing. I will self-review the Java parts myself.

2023-12-29 23:44 UTC, ryzhyk requested changes

2023-12-29 23:44 UTC, ryzhyk commented on crates/dbsp/src/circuit/runtime.rs
> +        message: String,
These changes to `WorkerPanic` will be superseded by my upcoming PR that will add panic information to `WorkerPanic`.

2023-12-29 23:44 UTC, ryzhyk commented on sql-to-dbsp-compiler/lib/sqllib/src/interval.rs
> +impl SerializeWithContext<SqlSerdeConfig> for ShortInterval {
A simpler way to implement this is to annotate the types with [`#serde[transparent]` ](https://serde.rs/container-attrs.html#transparent) and auto-devive `Serialize/Deserialize` impls and then use the `(de)serialize_without_context` macro to derive `(De)SerializeWithContext`

2023-12-29 23:44 UTC, ryzhyk commented on sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
> +pub fn append_to_upsert_handle<K, W>(data: &OrdZSet<K, W>, handle: UpsertHandle<K, bool>)
This should take `UpsertHandle` by reference.

2023-12-29 23:44 UTC, ryzhyk commented on sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
> +pub fn append_to_collection_handle<K, W>(data: &OrdZSet<K, W>, handle: CollectionHandle<K, W>)
Same here

2023-12-29 23:44 UTC, ryzhyk commented on sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
> +pub fn read_output_handle<K, W>(handle: OutputHandle<OrdZSet<K, W>>) -> OrdZSet<K, W>
Same here

2023-12-29 23:44 UTC, ryzhyk commented on sql-to-dbsp-compiler/lib/sqllib/src/lib.rs
> +        while !w.le0() {
This is not incorrect, but it should be sufficient to insert once.

2024-01-03 16:19 UTC, ryzhyk approved these changes

2024-01-03 16:20 UTC, ryzhyk commented
@mihaibudiu , I merged #1215 .  Can you please rebase and test before merging?

2024-01-05 19:40 UTC, mihaibudiu commented
Rebased, if the tests pass we should merge.

2024-01-08 18:39 UTC, mihaibudiu commented
This CI fails because it looks like the panic errors are not really deterministic
I will file an issue about it.

2024-01-08 22:12 UTC, merged