[SQL] Add functions for binary strings
feldera/feldera pull request #1264
Opened 2024-01-16 17:25 UTC by abhizer

* substring, overlay, octet_length, position

Is this a user-visible change (yes/no): yes (updates the docs)

#1262

2024-01-16 18:39 UTC, mihaibudiu requested changes

2024-01-16 18:39 UTC, mihaibudiu commented on docs/sql/binary.md
> +    <td>Returns the position of the first occurrence of binary1 in binary2</td>
I suspect the position is in bytes.
If the first offset is 1 you need to document that.

2024-01-16 18:39 UTC, mihaibudiu commented on docs/sql/binary.md
> +    <td>Returns the position of the first occurrence of binary1 in binary2</td>
you have to say what the return value is if the string is not found

2024-01-17 08:17 UTC, abhizer commented on sql-to-dbsp-compiler/lib/sqllib/src/binary.rs
> +    // indexing starts at 0
Yeah, that comment meant that rust indexing start at 0 and we have to convert from 1, I'll clarify it.

2024-01-17 08:18 UTC, abhizer commented on sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/VarbinaryTests.java
> +                        SELECT substring(x'123456', 0);
Yes.

2024-01-17 08:30 UTC, abhizer commented on docs/sql/binary.md
> +    <td>Generate a substring of binary starting at the given point. If the start position integer is negative, the substring starts at the position 0</td>
Postgres doesn't allow indexing with negative numbers, so that's what we do here. 
And yeah, it should be 1 instead of 0 in terms of SQL.

2024-01-17 08:44 UTC, abhizer commented on docs/sql/binary.md
> +    <td>Generate a binary string that replaces substring of binary1 with binary2. If the start position integer is negative, the new string will contain binary2 in position 0</td>
If FOR size is smaller than binary2 size, it still gets replaced by the entire binary2.

2024-01-17 10:09 UTC, abhizer commented on sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/VarbinaryTests.java
> +    public void testOctetLength() {
There are some here: https://github.com/postgres/postgres/blob/master/src/test/regress/expected/strings.out#L2544

2024-01-17 17:47 UTC, mihaibudiu commented on sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/VarbinaryTests.java
> +    public void testOctetLength() {
Can we steal these too?
They can be part of a separate PR.

2024-01-17 18:10 UTC, mihaibudiu approved these changes

2024-01-17 18:14 UTC, merged