[SQL] implement array_max, array_min functions
feldera/feldera pull request #1492
Opened 2024-03-04 16:02 UTC by abhizer

Is this a user-visible change (yes/no): yes

2024-03-04 16:04 UTC, abhizer commented on sql-to-dbsp-compiler/lib/sqllib/src/array.rs
> +}
I thought about creating a macro, but maybe its better to do it the next time we have to create similar functions.

2024-03-05 03:45 UTC, mihaibudiu requested changes

2024-03-05 03:45 UTC, mihaibudiu commented on sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java
> +    String getArrayCallNameWithElemNullability(RexCall call, DBSPExpression... ops) {
please add a JavaDoc explanation, this function name is complicated.

2024-03-05 03:45 UTC, mihaibudiu commented on sql-to-dbsp-compiler/lib/sqllib/src/array.rs
> +    array_max__(vector?)
max?

2024-03-05 03:45 UTC, mihaibudiu commented on sql-to-dbsp-compiler/lib/sqllib/src/array.rs
> +    array_max__(vector?)
there are no tests for these functions, that's why this mistake went unnoticed.

2024-03-05 03:48 UTC, mihaibudiu commented on sql-to-dbsp-compiler/lib/sqllib/src/array.rs
> +    array_max__(vector?)
there is also no documentation

2024-03-06 03:18 UTC, mihaibudiu commented on sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/ArrayTests.java
> +    @Test @Ignore("https://issues.apache.org/jira/browse/CALCITE-6275")
you should also link to an issue for our compiler

2024-03-06 03:18 UTC, mihaibudiu approved these changes

2024-03-06 03:19 UTC, mihaibudiu commented
too many conflicts to fix in the web editor, please fix them and resubmit

2024-03-06 12:52 UTC, merged