py: add register_local_view
feldera/feldera pull request #1884
Opened 2024-06-17 15:47 UTC by abhizer

Is this a user-visible change (yes/no): yes

2024-06-17 15:55 UTC, ryzhyk requested changes
Please also update `demo/project_demo10-FraudDetectionDeltaLake/run.py` and `demo/project_demo10-FraudDetectionDeltaLake/notebook.ipynb`.
And I think this will also require fixing a demo in the cloud repo.

2024-06-17 15:55 UTC, ryzhyk commented
cc @snkas

2024-06-18 11:04 UTC, snkas commented
I'd suggest adding an optional argument (`local: bool = True`) rather than having two functions.

Another suggestion is to add extra explanation between a local and (output) view:
```
Marking a view as local results in it no longer being materialized, potentially yielding performance benefit
over regular views at the cost of no longer being able to observe it (e.g., attach connectors to it).
This is particularly handy for intermediate views that are used in the implementation of other views,
a practice that benefits modularization of the SQL code.
```

2024-06-19 16:00 UTC, ryzhyk approved these changes

2024-06-19 17:21 UTC, merged