[SQL] Run sqllogictests by rotation, some every day
feldera/feldera pull request #2591
Opened 2024-09-26 23:36 UTC by mihaibudiu

This spreads the SLT tests over a number of days, using the current date to decide which tests to run.
Currently the tests are spread over 1 year, requiring running about 15K tests/day.
This is a trade-off between CI time and test coverage which we can tweak.

2024-09-26 23:37 UTC, mihaibudiu commented
Fixes #2578

2024-09-26 23:39 UTC, gz requested changes
This is horrible and should not be merged. We don't want CI to run a different set of tests every day. Non-deterministic failures are annoying enough already.

2024-09-26 23:41 UTC, mihaibudiu commented
these are not non-deterministic, they are just a different set of tests every day.

2024-09-26 23:43 UTC, mihaibudiu commented
I think the choice between never running them or running some of them every day is clear - we should run some of them.
In fact, this is how they were run the first time: manually, restarting on each failure. This is much better.

2024-09-26 23:43 UTC, gz commented
So CI will pass on some days and on some it won't (if there is a failure in one of these tests). If you happen to not run any CI on e.g. a Sunday you won't detect a failure either. If you are not around for a few days CI we won't be able to merge anything until it can be fixed or this test is disabled or we wait 24h.

2024-09-26 23:44 UTC, gz commented
There is another choice, we run them for every release, using a few VMs.

2024-09-26 23:45 UTC, mihaibudiu commented
if the CI doesn't pass it's because we have a real bug, we better know about it, and we better fix it.
and I haven't seen many days when the CI doesn't run.
the alternative algorithm is called the "ostrich algorithm": pretend that the bug is not there.
this issue was marked as "high priority"

2024-09-26 23:45 UTC, mihaibudiu commented
the tests need 6 weeks of CPU time on a machine like the CI machines
we don't have any tools to run tests like that

2024-09-26 23:48 UTC, gz commented
> we don't have any tools to run tests like that

I'm positive there are tools to run something in parallel on `n` VMs. This way of testing makes no sense, what's the assurance you get from doing it like this. You will never know if your version feldera that you are running is any better or not doing it this way.

2024-09-26 23:50 UTC, mihaibudiu commented
I filed a bug for a non-deterministic storage panic. Would you prefer me to delete the issue because the bug is non-deterministic? No one was looking at the panic message in my CI job when this happened. You don't really know whether it will happen in production or not.

2024-09-26 23:52 UTC, mihaibudiu commented
So we'll never run fuzzing tests?

2024-09-26 23:52 UTC, mihaibudiu commented
This is much better than fuzzing tests - these tests have validated outputs.

2024-09-26 23:53 UTC, lalithsuresh commented
This is actually a quintessential use for gnu-parallel. We can bring up an auto-scaled VM group in a k8s cluster, then fire off 100s of jobs to run the tests, and report back failures. Doing it before a release or with some other cadence makes a lot of sense to me.

2024-10-22 20:41 UTC, mihaibudiu commented
I think we agreed to merge this for now.

2024-10-22 21:40 UTC, lalithsuresh approved these changes

2024-10-22 23:14 UTC, mihaibudiu commented
@gz you need to approve this, or this can't be merged

2024-10-22 23:15 UTC, gz approved these changes

2024-10-23 10:58 UTC, merged