[SQL] use interned strings
feldera/feldera pull request #2608
Opened 2024-09-29 04:39 UTC by mihaibudiu

@ryzhyk @gz maybe you can review the Rust changes
The compiler changes are surprisingly few, which is actually a sign that the design is not bad.

2024-09-29 04:52 UTC, mihaibudiu commented
#Fixes #1637

2024-09-29 04:52 UTC, mihaibudiu commented
I would be very interested to see what this does to memory consumption and speed

2024-09-29 05:44 UTC, mihaibudiu commented
How can I force the skipped jobs run?

2024-09-29 06:10 UTC, ryzhyk commented
Hmm, something's wrong, I only tried it on one program so far, and it became 10x slower, and the memory hasn't improved.

2024-09-29 17:30 UTC, mihaibudiu commented
what program is that?
I don't expect I can misuse the library
we can work on perf, but if it doesn't help with memory, it's pointless
I have an idea how to improve

2025-02-03 05:59 UTC, mihaibudiu commented
This is now ready for review.
There is a config option `arcstring` which switches from `Interned` to `Arc<String>`, but I haven't tested it as much.
The default is `Interned` for strings.

2025-02-03 07:36 UTC, ryzhyk requested changes

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        Some(re) => re.is_match(&value.str()),
```suggestion
        Some(re) => re.is_match(value.str()),
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    let re = Regex::new(&pattern.str());
```suggestion
    let re = Regex::new(pattern.str());
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    re.map_or_else(|_| false, |re| re.is_match(&value.str()))
```suggestion
    re.map_or_else(|_| false, |re| re.is_match(value.str()))
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        .as_str()
```suggestion
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        .escape(escape.str().as_str())
```suggestion
        .escape(escape.str())
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    Like::<true>::like(value.str().as_str(), escaped.as_str()).unwrap()
```suggestion
    Like::<true>::like(value.str(), escaped).unwrap()
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    let pos = haystack.str().find(needle.str().as_str());
```suggestion
    let pos = haystack.str().find(needle.str());
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    let len = char_length_ref(&replacement.str());
```suggestion
    let len = char_length_ref(replacement.str());
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    } else if position > char_length_ref(&source.str()) {
```suggestion
    } else if position > char_length_ref(source.str()) {
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        let mut result = substring3___(source.clone(), 0, position - 1).str();
```suggestion
        let mut result = substring3___(source.clone(), 0, position - 1).to_string();
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        result += &*(replacement.str());
```suggestion
        result +=replacement.str();
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        result += &substring2__(source, position + remove).str();
```suggestion
        result += substring2__(source, position + remove).str();
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    SqlString::from(haystack.str().replace(&*needle.str(), &replacement.str()))
```suggestion
    SqlString::from(haystack.str().replace(needle.str(), replacement.str()))
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        .split(&*separators.str())
```suggestion
        .split(separators.str())
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        .collect::<Vec<String>>()
```suggestion
        .collect::<Vec<&str>>()
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        .join(&*separator.str())
```suggestion
        .join(separator.str())
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +            result.push_str(&separator.str())
```suggestion
            result.push_str(separator.str())
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
>          result.push_str(append.as_str());
```suggestion
        result.push_str(append);
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +            result.push_str(&separator.str())
```suggestion
            result.push_str(separator.str())
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        result.push_str(&append);
```suggestion
        result.push_str(append);
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    match serde_json::from_str::<Variant>(&value.str()) {
```suggestion
    match serde_json::from_str::<Variant>(value.str()) {
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    let re = Regex::new(&re.str()).ok();
```suggestion
    let re = Regex::new(re.str()).ok();
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +        Some(re) => SqlString::from_ref(&re.replace_all(&str.str(), &repl.str())),
```suggestion
        Some(re) => SqlString::from(re.replace_all(str.str(), repl.str())),
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    result.push_str(&left.str());
```suggestion
    result.push_str(left.str());
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    SqlString::from_ref(&result)
```suggestion
    result.push_str(sep.str());
    result.push_str(right.str());
    SqlString::from(result)
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/timestamp.rs
> +    let nt = NaiveDateTime::parse_from_str(&st.str(), &format.str());
```suggestion
    let nt = NaiveDateTime::parse_from_str(st.str(), format.str());
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/timestamp.rs
> +    return SqlString::from(date.to_dateTime().format(&format.str()).to_string());
```suggestion
    return SqlString::from(date.to_dateTime().format(format.str()));
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/timestamp.rs
> +    let nd = NaiveDate::parse_from_str(&st.str(), &format.str());
```suggestion
    let nd = NaiveDate::parse_from_str(st.str(), format.str());
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/timestamp.rs
> +    let nt = NaiveTime::parse_from_str(&st.str(), &format.str());
```suggestion
    let nt = NaiveTime::parse_from_str(st.str(), format.str());
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/variant.rs
> +                index.as_ref().to_string(),
This is a bit unfortunate. It should be possible to do map lookup by reference, but I'm not sure how to do this here.

2025-02-03 07:36 UTC, ryzhyk commented on demo/packaged/sql/08-dynamic-fga.udf.rs
> +    let expr = jmespath::compile(&condition.str())
```suggestion
    let expr = jmespath::compile(condition.str())
```

2025-02-03 07:36 UTC, ryzhyk commented on docs/sql/udf.md
> +| `VARCHAR`, `VARCHAR(n)`  | `feldera_sqllib::SQlString`             |
```suggestion
| `VARCHAR`, `VARCHAR(n)`  | `feldera_sqllib::SqlString`             |
```

2025-02-03 07:36 UTC, ryzhyk commented on docs/use_cases/fine_grained_authorization/dynamic.md
> +    let expr = jmespath::compile(&condition.str()).map_err(|e| println!("invalid jmes expression: {e}")).ok()?;
```suggestion
    let expr = jmespath::compile(condition.str()).map_err(|e| println!("invalid jmes expression: {e}")).ok()?;
```

2025-02-03 07:36 UTC, ryzhyk commented on sql-to-dbsp-compiler/lib/hashing/src/lib.rs
> +        let row_vec = sql_row.to_slt_strings(&self.format.str());
```suggestion
        let row_vec = sql_row.to_slt_strings(self.format.str());
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/adapters/src/test/data.rs
> +                                Variant::String(SqlString::from_ref(&variant.to_string())),
```suggestion
                                Variant::String(SqlString::from(variant.to_string())),
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/casts.rs
> +    match NaiveDate::parse_from_str(&value.str(), "%Y-%m-%d") {
```suggestion
    match NaiveDate::parse_from_str(value.str(), "%Y-%m-%d") {
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/casts.rs
> +    match NaiveTime::parse_from_str(&value.str(), "%H:%M:%S%.f") {
```suggestion
    match NaiveTime::parse_from_str(value.str(), "%H:%M:%S%.f") {
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/casts.rs
> +pub fn limit_or_size_string(value: String, size: i32, fixed: bool) -> SqlResult<SqlString> {
```suggestion
pub fn limit_or_size_string(value: &str, size: i32, fixed: bool) -> SqlResult<SqlString> {
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/casts.rs
> +    if let Some(captures) = DAYS_TO_HOURS.captures(&value.str()) {
```suggestion
    if let Some(captures) = DAYS_TO_HOURS.captures(value.str()) {
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/casts.rs
> +    if let Some(captures) = HOURS_TO_SECONDS.captures(&value.str()) {
```suggestion
    if let Some(captures) = HOURS_TO_SECONDS.captures(value.str()) {
```

2025-02-03 07:36 UTC, ryzhyk commented on crates/sqllib/src/casts.rs
> +    if let Ok(v) = NaiveDate::parse_from_str(&value.str(), "%Y-%m-%d") {
```suggestion
    if let Ok(v) = NaiveDate::parse_from_str(value.str(), "%Y-%m-%d") {
```

2025-02-03 16:05 UTC, ryzhyk requested changes
Also rkyv traits are missing, I think those are required for storage to work.

2025-02-03 20:29 UTC, ryzhyk commented on crates/sqllib/src/timestamp.rs
> +    return SqlString::from(date.to_dateTime().format(format.str()).to_string());
Is this `to_string()` needed?

2025-02-03 20:47 UTC, mihaibudiu commented on crates/sqllib/src/timestamp.rs
> +    return SqlString::from(date.to_dateTime().format(format.str()).to_string());
format returns some strange data type called `DelayedFormat`.

2025-02-04 08:04 UTC, ryzhyk approved these changes

2025-02-04 16:36 UTC, mihaibudiu commented on crates/sqllib/src/string.rs
> +    rkyv::Archive,
do these work for interned?
should they be feature-gated?

2025-02-04 18:00 UTC, ryzhyk commented on crates/sqllib/src/string.rs
> +    rkyv::Archive,
They don't I think. This probably won't compile with interned strings.

2025-02-05 04:43 UTC, merged